version: "3"
services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: wlanuser
      MONGO_INITDB_ROOT_PASSWORD: wlan2030
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: wlanuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: wlan2030
